### ISSUE TITLE
CMake Error: Unknown CMake command "get_target_export_arg".

### ISSUE THREAD

**Issue by MaxBubblegum47** [gcourchinoux/llvm-gaspard#1]
I have found a strange behavior: when I put the repo inside, for example LLVM 14.06, and I launch this command
`cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD='Chiara64' ../llvm-gaspard`

Everything goes fine, but if I want to add enable clang with the following command:
`cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS='clang' -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD='Chiara64' ../llvm-gaspard`

I got this error, and even if I re-launch the first command I still got the same error:
`CMake Error at /Users/lorenzostigliano/Desktop/llvm-project-llvmorg-14.0.6/clang/cmake/modules/AddClang.cmake:118 (get_target_export_arg):
  Unknown CMake command "get_target_export_arg".
Call Stack (most recent call first):
  /Users/lorenzostigliano/Desktop/llvm-project-llvmorg-14.0.6/clang/lib/Basic/CMakeLists.txt:39 (add_clang_library)`

**Comment by gcourchinoux** [comment]
Try first to compile llvm without clang. 

Simply create a directory build in the source repo and do : 

```
cmake ..
make -j4
```


After that you can compile clang . 

I have never tried to compile clang with llvm directly. 
I will try when I'm at home.

To explain : you have two target : 
Gaspard and Chiara64 

Chiara64 is not working well because it doesn't generate asm code and binary code to elf file. 
I don't know why, I'm stuck into a very strange error  when I run llc with --march=Chiara64. 
Chiara64 compile well and have the correct chiara64 instructions.

To resolve that, I have decided to port the Lanai target to chiara64 I don't have finished yet but it compiles well and generate a mix between lanai code and chiara64.

**Comment by MaxBubblegum47** [comment]
I understand your struggle I'm in a similar situation: I'm trying to do a port/remastered version of MBlaze Backend (Micro Blaze) for an FPGA project connected with my bachelor's degree thesis in Computer Science. I had so many problem with finding a small backend to study and I find Chiara64 quite nice because it is small and easy to navigate/understand (more easy than trying to understand RISCV).
I didn't have many problem creating the _.td files_, but I'm struggling so much to understand how to handle the remaining part. 
The aim for the thesis is just to do a little backend that generate assembly code for MBlaze.
In any case: I will apply your suggestion and update as soon as possible the issue. Thank you very much :)

**Comment by gcourchinoux** [comment]
You're welcome ! 

keep me in touch !

**Comment by MaxBubblegum47** [comment]
Okay I've kinda fixed the thing that I was trying to do, but I'm starting to build my backend in your same way (just compiling the_llvm_ part not all parts of the projects at once). Anyway if you want to connect your project with _clang_ you may need to follow this implementation: https://github.com/andresag01/llvm-project/commit/274cfea0f9662f0ed49f6132b0424323d0b11750#diff-185a32f321f9849c118053f8133d402a6f97ba3bf1a1f3ee14064d7716537c45
As you can see in this commit's history there are some lines of code that you need to add in the clang project, in order to be able to build as I did. I tried implementing _chiara64_ in the same way of _riscw_, and cmake goes fine, but I still have some error message at compile time. 
In the meanwhile I'm also working on my backend in order to get assembly code, but I have some error with the definition of `RegisterTarget` function inside `MCTargetDesc` folder. Idk seems like the project does not see that the function is its own function (is kinda builtin). If I do some progress I'll will share with you, but you can also find my repo at here: https://github.com/MaxBubblegum47/LLVM_13_MBLAZE
